# Generated by Django 3.2.18 on 2023-02-21 19:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0004_auto_20230221_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_quantity', models.FloatField()),
                ('product_cost', models.FloatField()),
                ('expected_loading_date', models.DateField()),
                ('nomination_status', models.CharField(choices=[('validation_pending', 'Validation Pening'), ('approval_pending', 'Approval Pending'), ('approved', 'Approved')], default='validation_pending', max_length=20)),
                ('advance', models.ManyToManyField(related_name='nomination', to='components.Advance')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomination', to='components.customer')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_nomination', to='components.location')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomination', to='components.driver')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomination', to='components.product')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_nomination', to='components.location')),
                ('tanker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomination', to='components.tanker')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomination', to='components.transporter')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomination', to='components.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loading_date', models.DateField()),
                ('loading_base_quantity', models.FloatField()),
                ('locading_l20_quantity', models.FloatField()),
                ('release_date', models.DateField()),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit', to='process.nomination')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NominationStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuel_quantity', models.FloatField()),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomination_station', to='process.nomination')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomination_station', to='components.station')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fullfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('off_loading_date', models.DateField()),
                ('off_loading_l20_quantity', models.FloatField()),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fullfillment', to='process.nomination')),
                ('transit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fullfillment', to='process.transit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
