# Generated by Django 3.2.18 on 2023-02-21 20:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_auto_20230221_2019'),
        ('process', '0002_auto_20230221_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_cash', to='components.currency')),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_cash', to='process.nomination')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdvanceFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuel_quantity', models.FloatField()),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_fuel', to='process.nomination')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_fuel', to='components.station')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdvanceOthers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.FloatField()),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_others', to='process.nomination')),
                ('sellable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_others', to='components.sellables')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='nominationstation',
            name='nomination',
        ),
        migrations.RemoveField(
            model_name='nominationstation',
            name='station',
        ),
        migrations.DeleteModel(
            name='Advance',
        ),
        migrations.DeleteModel(
            name='NominationStation',
        ),
    ]
