# Generated by Django 3.2.18 on 2023-02-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_auto_20230221_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='nomination_status',
            field=models.CharField(choices=[('validation_pending', 'Validation Pending'), ('approval_pending', 'Approval Pending'), ('approved', 'Approved')], default='validation_pending', max_length=20),
        ),
    ]
