# Generated by Django 3.2.16 on 2023-02-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_auto_20230221_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='stage',
            field=models.CharField(choices=[('nomination', 'Nomination'), ('transit', 'Transit'), ('offload', 'Offloaded')], default='nomination', max_length=20),
        ),
    ]
