# Generated by Django 3.2.16 on 2023-02-25 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_nomination_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullfillment',
            name='nomination',
        ),
        migrations.RemoveField(
            model_name='fullfillment',
            name='transit',
        ),
        migrations.RemoveField(
            model_name='transit',
            name='nomination',
        ),
        migrations.AddField(
            model_name='nomination',
            name='offload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nomination', to='process.fullfillment'),
        ),
        migrations.AddField(
            model_name='nomination',
            name='transit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nomination', to='process.transit'),
        ),
        migrations.AddField(
            model_name='transit',
            name='fullfillment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transit', to='process.fullfillment'),
        ),
    ]
