# Generated by Django 3.2.16 on 2023-02-25 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_auto_20230225_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='offload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomination', to='process.fullfillment'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='transit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomination', to='process.transit'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='fullfillment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transit', to='process.fullfillment'),
        ),
    ]
