# Generated by Django 3.2.16 on 2023-02-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_transit_invoice_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='transit',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
