# Generated by Django 3.2.16 on 2023-02-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0009_transit_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transit',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
