# Generated by Django 3.2.16 on 2023-02-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0010_transit_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullfillment',
            name='net_shortage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fullfillment',
            name='net_to_be_paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fullfillment',
            name='profiltability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fullfillment',
            name='shortage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fullfillment',
            name='shortage_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fullfillment',
            name='tolerance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
