# Generated by Django 3.2.16 on 2023-02-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0011_auto_20230225_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='sales_approved',
            field=models.BooleanField(default=False),
        ),
    ]
