# Generated by Django 3.2.16 on 2023-02-26 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0013_auto_20230226_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomination',
            name='product_cost',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='tanker_capacity',
        ),
        migrations.AlterField(
            model_name='nomination',
            name='transit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomination', to='process.transit', verbose_name='Rate (usd/ton)'),
        ),
    ]
