# Generated by Django 3.2.16 on 2023-02-26 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0014_auto_20230226_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='nomination_status',
            field=models.CharField(choices=[('validation_pending', 'Validation Pending'), ('approval_pending', 'Approval Pending'), ('approved', 'Approved')], default='validation_pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Rate (usd/ton)'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='transit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomination', to='process.transit'),
        ),
    ]
