# Generated by Django 3.2.16 on 2023-02-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0015_auto_20230226_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullfillment',
            name='dues_paid',
            field=models.BooleanField(default=False),
        ),
    ]
