# Generated by Django 3.2.18 on 2023-02-27 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0017_auto_20230227_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullfillment',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='transit',
            name='summary',
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
