# Generated by Django 3.2.18 on 2023-02-27 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0019_auto_20230227_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='summary',
        ),
        migrations.AlterField(
            model_name='fullfillment',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_offload', to='process.summary'),
        ),
        migrations.AlterField(
            model_name='nomination',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_nomination', to='process.summary'),
        ),
        migrations.AlterField(
            model_name='transit',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_transit', to='process.summary'),
        ),
    ]
