# Generated by Django 3.2.18 on 2023-02-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0021_auto_20230227_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullfillment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nomination',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transit',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
