# Generated by Django 3.2.18 on 2023-02-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0022_auto_20230227_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name_plural': 'Summary'},
        ),
        migrations.AddField(
            model_name='advancefuel',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='advancefuel',
            name='net_amount',
            field=models.FloatField(default=0),
        ),
    ]
