# Generated by Django 3.2.18 on 2023-03-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0023_auto_20230228_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancefuel',
            name='fuel_quantity',
        ),
        migrations.AddField(
            model_name='advancefuel',
            name='approved_fuel_quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='advancefuel',
            name='requested_fuel_quantity',
            field=models.FloatField(default=0),
        ),
    ]
