# Generated by Django 3.2.18 on 2023-03-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0025_auto_20230303_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancefuel',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advancefuel',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
