# Generated by Django 3.2.18 on 2023-03-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0026_auto_20230303_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullfillment',
            name='product_cost',
            field=models.FloatField(default=0, verbose_name='Product Cost (USD)'),
        ),
    ]
