# Generated by Django 3.2.18 on 2023-03-05 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0029_auto_20230305_0903'),
        ('process', '0027_fullfillment_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanceothers',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellables', to='components.currency'),
        ),
        migrations.AddField(
            model_name='advanceothers',
            name='exchange_rate',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='advanceothers',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellables', to='components.unit'),
        ),
        migrations.AddField(
            model_name='advanceothers',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
    ]
