# Generated by Django 3.2.18 on 2023-03-05 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0029_auto_20230305_0903'),
        ('process', '0028_auto_20230305_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancefuel',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='components.currency'),
        ),
        migrations.AddField(
            model_name='advancefuel',
            name='exchange_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='advancefuel',
            name='fuel_price',
            field=models.FloatField(default=0),
        ),
    ]
