# Generated by Django 3.2.18 on 2023-03-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0029_auto_20230305_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancecash',
            name='exchange_rate',
            field=models.FloatField(default=1),
        ),
    ]
