# Generated by Django 3.2.18 on 2023-03-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0030_alter_advancecash_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancecash',
            name='local_exchange_rate',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='advancefuel',
            name='local_exchange_rate',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='advanceothers',
            name='local_exchange_rate',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='fullfillment',
            name='local_exchange_rate',
            field=models.FloatField(default=1),
        ),
    ]
