# Generated by Django 3.2.18 on 2023-03-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0032_auto_20230310_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancefuel',
            name='exchange_rate',
            field=models.FloatField(default=1),
        ),
    ]
