# Generated by Django 3.2.18 on 2023-03-10 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0033_alter_advancefuel_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryinlocalcurrency',
            name='fullfillment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fullfillment_summary_local', to='process.fullfillment'),
        ),
        migrations.AlterField(
            model_name='summaryinlocalcurrency',
            name='nomination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nomination_summary_local', to='process.nomination'),
        ),
        migrations.AlterField(
            model_name='summaryinlocalcurrency',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_local', to='process.summary'),
        ),
        migrations.AlterField(
            model_name='summaryinlocalcurrency',
            name='transit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transit_summary_local', to='process.transit'),
        ),
    ]
