# Generated by Django 3.2.18 on 2023-03-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0034_auto_20230310_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='local_exchange_rate',
            field=models.FloatField(default=1),
        ),
    ]
