# Generated by Django 3.2.18 on 2023-03-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0036_auto_20230310_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='transit',
            name='invoice_value_local',
            field=models.FloatField(default=0),
        ),
    ]
