# Generated by Django 3.2.18 on 2023-03-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0037_transit_invoice_value_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullfillment',
            name='net_to_be_paid_local',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fullfillment',
            name='profiltability_local',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fullfillment',
            name='shortage_value_local',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
