# Generated by Django 3.2.18 on 2023-02-21 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_auto_20230220_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyexchange',
            name='currency',
        ),
        migrations.AddField(
            model_name='currencyexchange',
            name='from_currency',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_currency', to='components.currency'),
        ),
        migrations.AddField(
            model_name='currencyexchange',
            name='to_currency',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_currency', to='components.currency'),
        ),
        migrations.AlterField(
            model_name='currencyexchange',
            name='exchange_rate',
            field=models.IntegerField(editable=False),
        ),
    ]
