# Generated by Django 3.2.18 on 2023-02-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20230221_1910'),
        ('components', '0004_auto_20230221_1859'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advance',
        ),
    ]
