# Generated by Django 3.2.18 on 2023-02-23 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('components', '0011_auto_20230222_1407'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransporterOrganizationFuel',
            new_name='DiscountMaster',
        ),
        migrations.AlterModelOptions(
            name='discountmaster',
            options={},
        ),
    ]
