# Generated by Django 3.2.16 on 2023-02-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_auto_20230225_1659'),
        ('components', '0012_auto_20230223_0623'),
    ]

    operations = [
    ]
