# Generated by Django 3.2.16 on 2023-02-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0013_merge_0010_auto_20230225_1659_0012_auto_20230223_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
