# Generated by Django 3.2.16 on 2023-02-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0014_customer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanker',
            name='capacity',
            field=models.FloatField(default=0),
        ),
    ]
