# Generated by Django 3.2.16 on 2023-02-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0016_transporterpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransporterPayment',
        ),
    ]
