# Generated by Django 3.2.16 on 2023-02-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0018_transporterpayment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransporterPayment',
            new_name='TransporterBulkPayment',
        ),
        migrations.AddField(
            model_name='transporter',
            name='bulk_money',
            field=models.FloatField(default=0),
        ),
    ]
