# Generated by Django 3.2.16 on 2023-02-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0019_auto_20230226_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchange',
            name='exchange_rate',
            field=models.FloatField(default=0),
        ),
    ]
