# Generated by Django 3.2.18 on 2023-03-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0022_auto_20230302_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='exchange_rate',
            field=models.FloatField(default=0),
        ),
    ]
