# Generated by Django 3.2.18 on 2023-03-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0024_discountmaster_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporterbulkpayment',
            name='exchange_rate',
            field=models.FloatField(default=0),
        ),
    ]
