# Generated by Django 3.2.18 on 2023-03-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0025_transporterbulkpayment_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellables',
            name='exchange_rate',
            field=models.FloatField(default=0),
        ),
    ]
