# Generated by Django 3.2.18 on 2023-03-04 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0027_alter_sellables_exchange_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
        migrations.DeleteModel(
            name='CurrencyExchange',
        ),
    ]
