# Generated by Django 3.2.18 on 2023-03-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0028_auto_20230304_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellables',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='sellables',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='sellables',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='sellables',
            name='unit_price',
        ),
    ]
