# Generated by Django 3.2.18 on 2023-03-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0029_auto_20230305_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountmaster',
            name='local_exchange_rate',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='transporterbulkpayment',
            name='exchange_rate',
            field=models.FloatField(default=1),
        ),
    ]
