# Generated by Django 3.2.18 on 2023-03-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0030_auto_20230310_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='local_exchange_rate',
            field=models.FloatField(default=1),
        ),
    ]
