# Generated by Django 3.2.16 on 2023-02-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('validator', 'Validator'), ('operator', 'Operator'), ('admin', 'Admin'), ('sales_approver', 'Sales Approver')], default='admin', max_length=20, verbose_name='User Type'),
        ),
    ]
